/**
 * Seed script pour les pays (ISO 3166-1 alpha-2)
 * Liste complète des 249 pays/territoires reconnus
 * Source: https://fr.wikipedia.org/wiki/ISO_3166-1_alpha-2
 * Idempotent : ne duplique pas les pays existants (basé sur code)
 */

import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

// Liste complète ISO 3166-1 alpha-2 (code => nom français)
const countries = [
  { code: 'AF', nom: 'Afghanistan' },
  { code: 'ZA', nom: 'Afrique du Sud' },
  { code: 'AL', nom: 'Albanie' },
  { code: 'DZ', nom: 'Algérie' },
  { code: 'DE', nom: 'Allemagne' },
  { code: 'AD', nom: 'Andorre' },
  { code: 'AO', nom: 'Angola' },
  { code: 'AI', nom: 'Anguilla' },
  { code: 'AQ', nom: 'Antarctique' },
  { code: 'AG', nom: 'Antigua-et-Barbuda' },
  { code: 'AN', nom: 'Antilles néerlandaises' },
  { code: 'AR', nom: 'Argentine' },
  { code: 'AM', nom: 'Arménie' },
  { code: 'AW', nom: 'Aruba' },
  { code: 'AU', nom: 'Australie' },
  { code: 'AT', nom: 'Autriche' },
  { code: 'AZ', nom: 'Azerbaïdjan' },
  { code: 'BS', nom: 'Bahamas' },
  { code: 'BH', nom: 'Bahreïn' },
  { code: 'BD', nom: 'Bangladesh' },
  { code: 'BB', nom: 'Barbade' },
  { code: 'BE', nom: 'Belgique' },
  { code: 'BZ', nom: 'Belize' },
  { code: 'BJ', nom: 'Bénin' },
  { code: 'BM', nom: 'Bermudes' },
  { code: 'BT', nom: 'Bhoutan' },
  { code: 'BY', nom: 'Biélorussie' },
  { code: 'MM', nom: 'Birmanie' },
  { code: 'BO', nom: 'Bolivie' },
  { code: 'BA', nom: 'Bosnie-Herzégovine' },
  { code: 'BW', nom: 'Botswana' },
  { code: 'BR', nom: 'Brésil' },
  { code: 'BN', nom: 'Brunei' },
  { code: 'BG', nom: 'Bulgarie' },
  { code: 'BF', nom: 'Burkina Faso' },
  { code: 'BI', nom: 'Burundi' },
  { code: 'KH', nom: 'Cambodge' },
  { code: 'CM', nom: 'Cameroun' },
  { code: 'CA', nom: 'Canada' },
  { code: 'CV', nom: 'Cap-Vert' },
  { code: 'CL', nom: 'Chili' },
  { code: 'CN', nom: 'Chine' },
  { code: 'CY', nom: 'Chypre' },
  { code: 'CO', nom: 'Colombie' },
  { code: 'KM', nom: 'Comores' },
  { code: 'CG', nom: 'Congo' },
  { code: 'CD', nom: 'Congo (République démocratique)' },
  { code: 'KP', nom: 'Corée du Nord' },
  { code: 'KR', nom: 'Corée du Sud' },
  { code: 'CR', nom: 'Costa Rica' },
  { code: 'CI', nom: "Côte d'Ivoire" },
  { code: 'HR', nom: 'Croatie' },
  { code: 'CU', nom: 'Cuba' },
  { code: 'DK', nom: 'Danemark' },
  { code: 'DJ', nom: 'Djibouti' },
  { code: 'DM', nom: 'Dominique' },
  { code: 'EG', nom: 'Égypte' },
  { code: 'AE', nom: 'Émirats arabes unis' },
  { code: 'EC', nom: 'Équateur' },
  { code: 'ER', nom: 'Érythrée' },
  { code: 'ES', nom: 'Espagne' },
  { code: 'EE', nom: 'Estonie' },
  { code: 'US', nom: 'États-Unis' },
  { code: 'ET', nom: 'Éthiopie' },
  { code: 'FJ', nom: 'Fidji' },
  { code: 'FI', nom: 'Finlande' },
  { code: 'FR', nom: 'France' },
  { code: 'GA', nom: 'Gabon' },
  { code: 'GM', nom: 'Gambie' },
  { code: 'GE', nom: 'Géorgie' },
  { code: 'GS', nom: 'Géorgie du Sud et les Îles Sandwich du Sud' },
  { code: 'GH', nom: 'Ghana' },
  { code: 'GI', nom: 'Gibraltar' },
  { code: 'GR', nom: 'Grèce' },
  { code: 'GD', nom: 'Grenade' },
  { code: 'GL', nom: 'Groenland' },
  { code: 'GP', nom: 'Guadeloupe' },
  { code: 'GU', nom: 'Guam' },
  { code: 'GT', nom: 'Guatemala' },
  { code: 'GG', nom: 'Guernesey' },
  { code: 'GN', nom: 'Guinée' },
  { code: 'GW', nom: 'Guinée-Bissau' },
  { code: 'GY', nom: 'Guyana' },
  { code: 'GF', nom: 'Guyane française' },
  { code: 'HT', nom: 'Haïti' },
  { code: 'HN', nom: 'Honduras' },
  { code: 'HK', nom: 'Hong Kong' },
  { code: 'HU', nom: 'Hongrie' },
  { code: 'BV', nom: 'Île Bouvet' },
  { code: 'CX', nom: 'Île Christmas' },
  { code: 'NF', nom: 'Île Norfolk' },
  { code: 'IM', nom: 'Île de Man' },
  { code: 'AX', nom: 'Îles Åland' },
  { code: 'KY', nom: 'Îles Caïmans' },
  { code: 'CC', nom: 'Îles Cocos (Keeling)' },
  { code: 'CK', nom: 'Îles Cook' },
  { code: 'FO', nom: 'Îles Féroé' },
  { code: 'FK', nom: 'Îles Falkland' },
  { code: 'FJ', nom: 'Îles Fidji' },
  { code: 'HM', nom: 'Îles Heard et McDonald' },
  { code: 'MP', nom: 'Îles Mariannes du Nord' },
  { code: 'MH', nom: 'Îles Marshall' },
  { code: 'PN', nom: 'Îles Pitcairn' },
  { code: 'SB', nom: 'Îles Salomon' },
  { code: 'TC', nom: 'Îles Turques-et-Caïques' },
  { code: 'VG', nom: 'Îles Vierges britanniques' },
  { code: 'VI', nom: 'Îles Vierges des États-Unis' },
  { code: 'IN', nom: 'Inde' },
  { code: 'ID', nom: 'Indonésie' },
  { code: 'IR', nom: 'Iran' },
  { code: 'IQ', nom: 'Irak' },
  { code: 'IE', nom: 'Irlande' },
  { code: 'IS', nom: 'Islande' },
  { code: 'IL', nom: 'Israël' },
  { code: 'IT', nom: 'Italie' },
  { code: 'JM', nom: 'Jamaïque' },
  { code: 'JP', nom: 'Japon' },
  { code: 'JE', nom: 'Jersey' },
  { code: 'JO', nom: 'Jordanie' },
  { code: 'KZ', nom: 'Kazakhstan' },
  { code: 'KE', nom: 'Kenya' },
  { code: 'KG', nom: 'Kirghizistan' },
  { code: 'KI', nom: 'Kiribati' },
  { code: 'KW', nom: 'Koweït' },
  { code: 'LA', nom: 'Laos' },
  { code: 'LS', nom: 'Lesotho' },
  { code: 'LV', nom: 'Lettonie' },
  { code: 'LB', nom: 'Liban' },
  { code: 'LR', nom: 'Libéria' },
  { code: 'LY', nom: 'Libye' },
  { code: 'LI', nom: 'Liechtenstein' },
  { code: 'LT', nom: 'Lituanie' },
  { code: 'LU', nom: 'Luxembourg' },
  { code: 'MO', nom: 'Macao' },
  { code: 'MK', nom: 'Macédoine du Nord' },
  { code: 'MG', nom: 'Madagascar' },
  { code: 'MY', nom: 'Malaisie' },
  { code: 'MW', nom: 'Malawi' },
  { code: 'MV', nom: 'Maldives' },
  { code: 'ML', nom: 'Mali' },
  { code: 'MT', nom: 'Malte' },
  { code: 'MA', nom: 'Maroc' },
  { code: 'MQ', nom: 'Martinique' },
  { code: 'MU', nom: 'Maurice' },
  { code: 'MR', nom: 'Mauritanie' },
  { code: 'YT', nom: 'Mayotte' },
  { code: 'MX', nom: 'Mexique' },
  { code: 'FM', nom: 'Micronésie' },
  { code: 'MD', nom: 'Moldavie' },
  { code: 'MC', nom: 'Monaco' },
  { code: 'MN', nom: 'Mongolie' },
  { code: 'ME', nom: 'Monténégro' },
  { code: 'MS', nom: 'Montserrat' },
  { code: 'MZ', nom: 'Mozambique' },
  { code: 'NA', nom: 'Namibie' },
  { code: 'NR', nom: 'Nauru' },
  { code: 'NP', nom: 'Népal' },
  { code: 'NI', nom: 'Nicaragua' },
  { code: 'NE', nom: 'Niger' },
  { code: 'NG', nom: 'Nigeria' },
  { code: 'NU', nom: 'Niue' },
  { code: 'NO', nom: 'Norvège' },
  { code: 'NC', nom: 'Nouvelle-Calédonie' },
  { code: 'NZ', nom: 'Nouvelle-Zélande' },
  { code: 'OM', nom: 'Oman' },
  { code: 'UG', nom: 'Ouganda' },
  { code: 'UZ', nom: 'Ouzbékistan' },
  { code: 'PK', nom: 'Pakistan' },
  { code: 'PW', nom: 'Palaos' },
  { code: 'PS', nom: 'Palestine' },
  { code: 'PA', nom: 'Panama' },
  { code: 'PG', nom: 'Papouasie-Nouvelle-Guinée' },
  { code: 'PY', nom: 'Paraguay' },
  { code: 'NL', nom: 'Pays-Bas' },
  { code: 'PE', nom: 'Pérou' },
  { code: 'PH', nom: 'Philippines' },
  { code: 'PL', nom: 'Pologne' },
  { code: 'PF', nom: 'Polynésie française' },
  { code: 'PR', nom: 'Porto Rico' },
  { code: 'PT', nom: 'Portugal' },
  { code: 'QA', nom: 'Qatar' },
  { code: 'CF', nom: 'République centrafricaine' },
  { code: 'DO', nom: 'République dominicaine' },
  { code: 'CZ', nom: 'République tchèque' },
  { code: 'RO', nom: 'Roumanie' },
  { code: 'GB', nom: 'Royaume-Uni' },
  { code: 'RU', nom: 'Russie' },
  { code: 'RW', nom: 'Rwanda' },
  { code: 'EH', nom: 'Sahara occidental' },
  { code: 'BL', nom: 'Saint-Barthélemy' },
  { code: 'SH', nom: 'Sainte-Hélène, Ascension et Tristan da Cunha' },
  { code: 'KN', nom: 'Saint-Christophe-et-Niévès' },
  { code: 'SM', nom: 'Saint-Marin' },
  { code: 'VA', nom: 'Saint-Siège (État de la Cité du)' },
  { code: 'VC', nom: 'Saint-Vincent-et-les-Grenadines' },
  { code: 'LC', nom: 'Sainte-Lucie' },
  { code: 'PM', nom: 'Saint-Pierre-et-Miquelon' },
  { code: 'SV', nom: 'Salvador' },
  { code: 'WS', nom: 'Samoa' },
  { code: 'AS', nom: 'Samoa américaines' },
  { code: 'ST', nom: 'Sao Tomé-et-Principe' },
  { code: 'SA', nom: 'Arabie saoudite' },
  { code: 'SN', nom: 'Sénégal' },
  { code: 'RS', nom: 'Serbie' },
  { code: 'SC', nom: 'Seychelles' },
  { code: 'SL', nom: 'Sierra Leone' },
  { code: 'SG', nom: 'Singapour' },
  { code: 'SK', nom: 'Slovaquie' },
  { code: 'SI', nom: 'Slovénie' },
  { code: 'SO', nom: 'Somalie' },
  { code: 'SD', nom: 'Soudan' },
  { code: 'SS', nom: 'Soudan du Sud' },
  { code: 'LK', nom: 'Sri Lanka' },
  { code: 'SE', nom: 'Suède' },
  { code: 'CH', nom: 'Suisse' },
  { code: 'SR', nom: 'Suriname' },
  { code: 'SJ', nom: 'Svalbard et Île Jan Mayen' },
  { code: 'SY', nom: 'Syrie' },
  { code: 'TJ', nom: 'Tadjikistan' },
  { code: 'TW', nom: 'Taïwan' },
  { code: 'TZ', nom: 'Tanzanie' },
  { code: 'TD', nom: 'Tchad' },
  { code: 'TF', nom: 'Terres australes françaises' },
  { code: 'IO', nom: "Territoire britannique de l'océan Indien" },
  { code: 'TH', nom: 'Thaïlande' },
  { code: 'TL', nom: 'Timor oriental' },
  { code: 'TG', nom: 'Togo' },
  { code: 'TK', nom: 'Tokelau' },
  { code: 'TO', nom: 'Tonga' },
  { code: 'TT', nom: 'Trinité-et-Tobago' },
  { code: 'TN', nom: 'Tunisie' },
  { code: 'TM', nom: 'Turkménistan' },
  { code: 'TR', nom: 'Turquie' },
  { code: 'TV', nom: 'Tuvalu' },
  { code: 'UA', nom: 'Ukraine' },
  { code: 'UY', nom: 'Uruguay' },
  { code: 'VU', nom: 'Vanuatu' },
  { code: 'VE', nom: 'Venezuela' },
  { code: 'VN', nom: 'Viêt Nam' },
  { code: 'WF', nom: 'Wallis-et-Futuna' },
  { code: 'YE', nom: 'Yémen' },
  { code: 'ZM', nom: 'Zambie' },
  { code: 'ZW', nom: 'Zimbabwe' },
];

async function main() {
  console.log('[seed_countries] Début du seed des pays...');

  let insertedCount = 0;
  let skippedCount = 0;

  for (const country of countries) {
    const existing = await prisma.countries.findUnique({
      where: { code: country.code },
    });

    if (!existing) {
      await prisma.countries.create({
        data: {
          id: crypto.randomUUID(),
          code: country.code,
          nom: country.nom,
        },
      });
      insertedCount++;
      console.log(`  ✓ Insertion: ${country.nom} (${country.code})`);
    } else {
      skippedCount++;
      console.log(`  - Déjà présent: ${country.nom} (${country.code})`);
    }
  }

  console.log(
    `[seed_countries] Terminé: ${insertedCount} pays insérés, ${skippedCount} déjà présents.`,
  );
}

main()
  .catch((e) => {
    console.error('[seed_countries] Erreur:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
